### ISSUE TITLE
Not work for me (Eclipse 4.2)

### ISSUE THREAD

**Issue by johnkil** [rogerdudler/eclipse-ui-themes#1]
I did everything according to instructions, but nothing has changed.

**Comment by rogerdudler** [comment]
Can you provide some more information, complete path where you extracted the zip and some OS information.

**Comment by johnkil** [comment]
I extracted the zip into eclipse dropins folder. I use Mac OS X 10.7.4.

**Comment by rogerdudler** [comment]
Sorry for asking, but just to be sure: You don't see the theme under Preferences > General > Appearance > (Dropdown). And you double-checked that it's the right eclipse folder under Applications?

**Comment by johnkil** [comment]
Theme is visible from the settings (Preferences > General > Appearance > Theme > Dark Juno), but if I used it, nothing happens.

**Comment by rogerdudler** [comment]
Can you check the Error Log of your Eclipse?

**Comment by urjitbhatia** [comment]
With the risk of stupid comment, but did you restart Eclipse? I am on Mac 10.6.8 and it worked perfectly fine. If you go to Help->install new software->see already installed->Configuration copy the logs and search for something like this: 

**\* Plug-in Registry:
com.github.eclipsecolortheme (0.11.1.201106241814) "Eclipse Color Theme" [Starting]
com.github.eclipsecolortheme.themes (1.0.0.qualifier) "Eclipse UI Themes" [Starting]

**Comment by johnkil** [comment]
**\* Plug-in Registry:
com.github.eclipsecolortheme (0.11.1.201106241814) "Eclipse Color Theme" [Active]
com.github.eclipsecolortheme.themes (1.0.0.201207112226) "Eclipse UI Themes" [Starting]

**Comment by johnkil** [comment]
Yes. I did restart but it does not help

**Comment by johnkil** [comment]
There's (error log) nothing that could help unfortunately. I checked several times.

**Comment by rogerdudler** [comment]
Which Java Version are you using?

**Comment by johnkil** [comment]
1.6

**Comment by LawlietS** [comment]
same problem here - also with max os x 10.7.4

**Comment by johnkil** [comment]
Theme appears in the list of available themes - http://i45.tinypic.com/vo8rxl.png
After restart there is a thin black stripe on top - http://i45.tinypic.com/sym7eu.png

**Comment by andymaster01** [comment]
Same issue for me .. but in my case I'm on WinXP SP3 with Juno and Eclipse Color Theme Installed

**Comment by rogerdudler** [comment]
that's interesting, that might be a bug of Eclipse itself then, I'll check that with the Eclipse guys, maybe they know the problem. 

## 

Roger Dudler
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by urjitbhatia** [comment]
Try changing eclipse version to 4.2 in plugin.xml? @rogerdudler  I think its 3.4 right now? Would that cause some problems?

**Comment by mwergles** [comment]
Same problem here :(

Arch Linux
Java version "1.7.0_05"
Eclipse SDK - Version: 4.2.0 - Build id: I20120608-1400

**Comment by golimpio** [comment]
When I select the theme, I get the following exception:

```
null
Error
Thu Jul 12 12:21:24 EST 2012
Problems occurred when invoking code from plug-in: "org.eclipse.jface".

java.lang.NullPointerException
    at org.eclipse.e4.ui.preferences.CSSEditorPreferences.updateInput(CSSEditorPreferences.java:204)
    at org.eclipse.e4.ui.preferences.CSSEditorPreferences.setSelection(CSSEditorPreferences.java:100)
    at org.eclipse.ui.internal.dialogs.ViewsPreferencePage$2.selectionChanged(ViewsPreferencePage.java:81)
    at org.eclipse.jface.viewers.Viewer$2.run(Viewer.java:164)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:49)
    at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:175)
    at org.eclipse.jface.viewers.Viewer.fireSelectionChanged(Viewer.java:162)
    at org.eclipse.jface.viewers.StructuredViewer.updateSelection(StructuredViewer.java:2188)
    at org.eclipse.jface.viewers.StructuredViewer.handleSelect(StructuredViewer.java:1211)
    at org.eclipse.jface.viewers.StructuredViewer$4.widgetSelected(StructuredViewer.java:1241)
    at org.eclipse.jface.util.OpenStrategy.fireSelectionEvent(OpenStrategy.java:239)
    at org.eclipse.jface.util.OpenStrategy.access$4(OpenStrategy.java:233)
    at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:403)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1053)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4169)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3758)
    at org.eclipse.jface.window.Window.runEventLoop(Window.java:825)
    at org.eclipse.jface.window.Window.open(Window.java:801)
    at org.eclipse.ui.internal.dialogs.WorkbenchPreferenceDialog.open(WorkbenchPreferenceDialog.java:215)
    at org.eclipse.ui.internal.OpenPreferencesAction.run(OpenPreferencesAction.java:65)
    at org.eclipse.jface.action.Action.runWithEvent(Action.java:498)
    at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:584)
    at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:501)
    at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:411)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1053)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4169)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3758)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1022)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:916)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:86)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:585)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:540)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:124)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1438)
```

Windows 7 x64
jdk1.6.0_29

**Comment by LeeSanghoon** [comment]
I've got an error when I selected "Dark Juno" theme.

java.io.FileNotFoundException: /themes/css/juno.css

And I saw a plugin file "com.github.eclipsecolortheme.themes_1.0.0.201207112226.jar".
It did NOT have juno.css file.

I think you should check 'themes' folder in plugin build property.

**Comment by xseignard** [comment]
Hi, I had the same issue that @golimpio
So I added the themes folder in the build.properties and it works quite ok.

I'll try to enrich the theme without installing the http://www.eclipsecolorthemes.org/ plugin

Here is the current status of the Dark Juno theme on ubuntu
https://dl.dropbox.com/u/17657227/darkUI.png

It's a great start! Keep the good the job!

**Comment by rogerdudler** [comment]
Thanks for all the comments, i fixed the release, can you try again - https://github.com/downloads/eclipse-color-theme/eclipse-ui-themes/com.github.eclipsecolortheme.themes_1.0.0.201207121019.zip

**Comment by AlQuraian** [comment]
It's working fine now, Thanks a lot Roger.

**Comment by johnkil** [comment]
It's working but I see the following picture - http://i50.tinypic.com/2uo5jl2.jpg. it should be or something I did?

**Comment by jetztgradnet** [comment]
I also still see a white editor area like @johnkil posted above. 

Some system information: 
eclipse.buildId=I20120608-1400
os.arch=amd64
os.name=Windows 7
os.version=6.1
osgi.arch=x86_64
java.version=1.7.0_04
java.vm.version=23.0-b21
org.osgi.framework.os.name=Windows7
org.osgi.framework.os.version=6.1.0
org.osgi.framework.processor=x86-64

**Comment by xseignard** [comment]
@jetztgradnet as stated there : https://github.com/eclipse-color-theme/eclipse-ui-themes/blob/master/README.md
the editor styling is handled by classical eclipse configuration.

Just go to http://eclipsecolorthemes.org/?view=plugin to install the plugin and then choose a dark color editor theme that fit your needs.

**Comment by johnkil** [comment]
Yes but it is not required by developers, if I understand correctly

**Comment by jetztgradnet** [comment]
Thanks, I missed that part. 

Maybe you could update the readme to make this stand out a bit more?
